- name: "claude_3.7-sonnet"
  auth: "anthropic"
  model:
    type: "anthropic"
    model: "claude-3-7-sonnet-20250219"
- name: "claude_3.5-haiku"
  auth: "anthropic"
  model:
    type: "anthropic"
    model: "claude-3-5-haiku-20241022"
- name: "claude_3.5-sonnet-v2"
  auth: "anthropic"
  model:
    type: "anthropic"
    model: "claude-3-5-sonnet-20241022"
- name: "claude_3.5-sonnet"
  auth: "anthropic"
  model:
    type: "anthropic"
    model: "claude-3-5-sonnet-20240620"
- name: "claude_3-opus"
  auth: "anthropic"
  model:
    type: "anthropic"
    model: "claude-3-opus-20240229"
- name: "claude_3-sonnet"
  auth: "anthropic"
  model:
    type: "anthropic"
    model: "claude-3-sonnet-20240229"
- name: "claude_3-haiku"
  auth: "anthropic"
  model:
    type: "anthropic"
    model: "claude-3-haiku-20240307"